remote_theme: daattali/beautiful-jekyll@6.0.1
title: VCE Data Analytics Resource Page
description: A resource for Heathmont College students studying VCE Applied Computing - Data Analytics Unit 3 & 4.
baseurl: "/"
url: "https://heathmontdataanalytics.github.io"
markdown: GFM
mermaid: true
class: wide

# Plugins
plugins:
  - jekyll-feed
  - jekyll-spaceship

# Navigation links
navigation:
  - title: Home
    url: /
  - title: Databases & SQL
    url: /topics/databases
  - title: Spreadsheets
    url: /topics/spreadsheets
  - title: Visualisations
    url: /topics/visualisations
  - title: Project Management
    url: /topics/project-management
  - title: Legal & Ethical
    url: /topics/legal-ethical
  - title: Security
    url: /topics/security
  - title: Machine Learning
    url: /topics/machine-learning
