remote_theme: "mmistakes/minimal-mistakes@4.26.2"
title: VCE Data Analytics Resource Page
description: A resource for Heathmont College students studying VCE Applied Computing - Data Analytics Unit 3 & 4.
baseurl: "/"
url: "https://heathmontdataanalytics.github.io"
class: wide

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache


# Navigation links
navigation:
  - title: Home
    url: /
  - title: Databases and SQL
    url: /topics/databases
  - title: Spreadsheets
    url: /topics/spreadsheets
  - title: Visualisations
    url: /topics/visualisations
  - title: Project Management
    url: /topics/project-management
  - title: Legal and Ethical
    url: /topics/legal-ethical
  - title: Security
    url: /topics/security
  - title: Machine Learning
    url: /topics/machine-learning
